import { Component, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { PageHeader } from '../../../shared/components/page-header/page-header';
import { ButtonModule } from 'primeng/button';

interface ReportType { id: string; title: string; description: string; icon: string; color: string; }
interface GeneratedReport { id: string; name: string; generatedBy: string; date: string; format: string; }

@Component({
  selector: 'app-accountant-reports',
  standalone: true,
  imports: [CommonModule, PageHeader, ButtonModule],
  template: `
    <div class="space-y-6 animate-fade-in">
      <app-page-header title="Financial Reports" subtitle="Generate and download financial reports" />

      <!-- Report Types Grid -->
      <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4 stagger-children">
        @for (r of reportTypes; track r.id) {
          <div class="glass-card p-5 space-y-3 hover:border-indigo-300 dark:hover:border-indigo-700 transition-all group cursor-pointer">
            <div class="flex items-center gap-3">
              <div class="w-10 h-10 rounded-xl flex items-center justify-center text-white" [style.background]="r.color">
                <i [class]="r.icon"></i>
              </div>
              <h4 class="font-bold text-slate-800 dark:text-white group-hover:text-indigo-600 transition-colors">{{ r.title }}</h4>
            </div>
            <p class="text-xs text-slate-500 leading-relaxed">{{ r.description }}</p>
            <div class="flex items-center gap-2 pt-2 border-t border-slate-100 dark:border-slate-800">
              <select class="flex-1 p-1.5 rounded-lg border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-900 text-[10px]">
                <option>Last Month</option><option>Last Quarter</option><option>Last Year</option><option>Custom Range</option>
              </select>
              <button pButton label="Generate" icon="pi pi-download" class="p-button-sm rounded-lg bg-indigo-600 border-indigo-600 text-white text-xs" (click)="generateReport(r)"></button>
            </div>
          </div>
        }
      </div>

      <!-- Recently Generated -->
      <div class="glass-card p-5 space-y-4">
        <h4 class="text-sm font-bold text-slate-800 dark:text-white uppercase tracking-wider"><i class="pi pi-history mr-2 text-slate-400"></i>Recently Generated</h4>
        <div class="overflow-x-auto">
          <table class="w-full text-sm">
            <thead><tr class="border-b border-slate-200 dark:border-slate-700 text-left">
              <th class="p-3 text-xs font-semibold text-slate-500 uppercase">Report</th><th class="p-3 text-xs font-semibold text-slate-500 uppercase">Generated By</th><th class="p-3 text-xs font-semibold text-slate-500 uppercase">Date</th><th class="p-3 text-xs font-semibold text-slate-500 uppercase">Format</th><th class="p-3 text-xs font-semibold text-slate-500 uppercase">Action</th>
            </tr></thead>
            <tbody>
              @for (g of generated(); track g.id) {
                <tr class="border-b border-slate-100 dark:border-slate-800">
                  <td class="p-3 font-bold text-slate-800 dark:text-white">{{ g.name }}</td>
                  <td class="p-3 text-slate-500">{{ g.generatedBy }}</td>
                  <td class="p-3 text-slate-500">{{ g.date }}</td>
                  <td class="p-3"><span class="px-2 py-0.5 rounded text-[10px] font-bold uppercase bg-green-100 text-green-700">{{ g.format }}</span></td>
                  <td class="p-3"><button pButton icon="pi pi-download" class="p-button-sm p-button-text p-button-rounded"></button></td>
                </tr>
              }
            </tbody>
          </table>
        </div>
      </div>
    </div>
  `, styles: [``]
})
export class AccountantReports {
  reportTypes: ReportType[] = [
    { id: 'rt1', title: 'Profit & Loss Statement', description: 'Complete income and expense breakdown with net profit calculation', icon: 'pi pi-chart-line', color: 'linear-gradient(135deg, #6366f1, #4f46e5)' },
    { id: 'rt2', title: 'Balance Sheet', description: 'Assets, liabilities, and equity overview at a glance', icon: 'pi pi-chart-bar', color: 'linear-gradient(135deg, #10b981, #059669)' },
    { id: 'rt3', title: 'Cash Flow Statement', description: 'Track cash inflows and outflows across operations', icon: 'pi pi-dollar', color: 'linear-gradient(135deg, #f59e0b, #d97706)' },
    { id: 'rt4', title: 'Aging Report', description: 'Outstanding dues categorized by aging buckets', icon: 'pi pi-clock', color: 'linear-gradient(135deg, #ef4444, #dc2626)' },
    { id: 'rt5', title: 'GST Summary Report', description: 'Monthly GST collected, input credit, and net liability', icon: 'pi pi-file', color: 'linear-gradient(135deg, #8b5cf6, #7c3aed)' },
    { id: 'rt6', title: 'Collection Report', description: 'Rent collection rate, pending dues, and payment modes', icon: 'pi pi-wallet', color: 'linear-gradient(135deg, #ec4899, #db2777)' },
  ];
  generated = signal<GeneratedReport[]>([
    { id: 'g1', name: 'P&L Statement — May 2026', generatedBy: 'Accountant', date: 'Jun 1, 2026', format: 'PDF' },
    { id: 'g2', name: 'GST Summary — May 2026', generatedBy: 'Accountant', date: 'Jun 1, 2026', format: 'Excel' },
    { id: 'g3', name: 'Aging Report — Q1 2026', generatedBy: 'Owner', date: 'Apr 2, 2026', format: 'PDF' },
    { id: 'g4', name: 'Collection Report — Apr 2026', generatedBy: 'Accountant', date: 'May 1, 2026', format: 'PDF' },
  ]);
  generateReport(r: ReportType) {
    this.generated.update(list => [{ id: 'g' + Date.now(), name: r.title + ' — June 2026', generatedBy: 'Accountant', date: new Date().toLocaleDateString('en-IN', { month: 'short', day: 'numeric', year: 'numeric' }), format: 'PDF' }, ...list]);
  }
}
